### ISSUE TITLE
Fix Orb exception

### ISSUE THREAD

**Issue by IDemiurge** [IDemiurge/battlecraft#75]
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Array is empty.
 at com.badlogic.gdx.utils.Array.pop(Array.java:296)
 at com.badlogic.gdx.scenes.scene2d.utils.ScissorStack.popScissors(ScissorStack.java:77)
 at main.libgdx.gui.panels.dc.actionpanel.OrbElement.draw(OrbElement.java:63)

**Comment by mephistopheles-repo** [comment]
moved to youtrack
